# Name
Please write your name down here:

Peter Brederlow

**Pandas Basics**

In this notebook we will familiarize ourselves with some basic `pandas` objects and operations which we'll use often later in the practical course.

Pandas has extensive online documentation, and you may find their [10 Minutes Introduction](http://pandas.pydata.org/pandas-docs/stable/10min.html) and their [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) especially useful.

Also take a look at [Jupyter keyboard shortcuts](https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/) to help you format your notebooks efficiently.

In [2]:
import pandas as pd
import numpy as np
pd.set_option('future.no_silent_downcasting', True)

/var/folders/vm/8qbbn1f91lb9f4yl4gd82lch0000gn/T/ipykernel_98364/1153847508.py:3: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.set_option('future.no_silent_downcasting', True)

In [3]:
# Test declarations, do not delete!

# Series objects

## Create a pandas `Series` object named `s` with the following data:

| s   |
|-----|
| 3.0 |
| 1.5 |
| 4.3 |
| 8.2 |
| 0.9 |

In [4]:
# YOUR CODE HERE
s = pd.Series([3.0, 1.5, 4.3, 8.2, 0.9])

In [5]:
assert 's' in locals()
# test for type
print(s.dtype)

float64

In [6]:
# test for content
print(s)

0    3.0
1    1.5
2    4.3
3    8.2
4    0.9
dtype: float64

## Access its first value
And store it as variable `first`.

In [7]:
# YOUR CODE HERE
first = s[0]
print(first)

3.0

In [8]:
assert 'first' in locals()
# test for value
print(first.dtype)

float64

## Access its last value
And store it as variable `last`.

In [9]:
# YOUR CODE HERE
last = s.iloc[-1]
print(last)

0.9

In [10]:
assert 'last' in locals()
# test for value
print(last.dtype)

float64

## Sort it in ascending and descending order
Store the ascending series as `asc` and the descending series as `desc`.

In [11]:
# YOUR CODE HERE
asc = s.sort_values()
print(asc)

desc = s.sort_values(ascending=False)
print(desc)

4    0.9
1    1.5
0    3.0
2    4.3
3    8.2
dtype: float64
3    8.2
2    4.3
0    3.0
1    1.5
4    0.9
dtype: float64

In [12]:
assert 'asc' in locals()
assert type(asc) == pd.Series

In [13]:
assert 'desc' in locals()
assert type(desc) == pd.Series

## Calculate its mean and standard deviation
Store the mean in `avg` and the standard deviation in `stdev`.

In [14]:
# YOUR CODE HERE
avg = s.mean()
print(avg)
stdev = s.std()
print(stdev)

3.5799999999999996
2.90292955477738

In [15]:
assert 'avg' in locals()

In [16]:
assert 'stdev' in locals()

# DataFrame objects, accessing values

Create a `DataFrame` named `df_species` of the following table:

|(index) |species |weight  |legs |
|--------|--|---|----|
|0       |human |62  |2 |
|1       |cat |4  |4 |
|2       |mouse |0.02  |4 |
|3       |dog |20 |4 |
|4       |mole |0.09  |4 |
|5       |train |200000 |NaN |
|6       |bee |0.0001 |6  |
|7       |elephant |3000 |4 |

<div class="alert alert-block alert-warning"><b>Warning: </b> Do not use <code>pd.NA</code> to represent missing values, because this will break the behavior of multiple functions. </div>

In [17]:
# YOUR CODE HERE
df_species = pd.DataFrame({'species': ['human', 'cat', 'mouse', 'dog', 'mole', 'train', 'bee', 'elephant'], 
                           'weight': [62, 4, 0.02, 20, 0.09, 200000, 0.0001, 3000],
                           'legs': [2, 4, 4, 4, 4, np.nan, 6, 4]})
print(df_species)

    species       weight  legs
0     human      62.0000   2.0
1       cat       4.0000   4.0
2     mouse       0.0200   4.0
3       dog      20.0000   4.0
4      mole       0.0900   4.0
5     train  200000.0000   NaN
6       bee       0.0001   6.0
7  elephant    3000.0000   4.0

In [18]:
assert 'df_species' in locals()
# test for content

## Sort `df_species` by `weight` and overwrite it.

In [19]:
# YOUR CODE HERE
df_species = df_species.sort_values('weight') #assuming ascending order

In [20]:
assert 'df_species' in locals()
# test for content

## Access the 3rd row of `df_species` as a `Series` object
And store it in `third`.

In [80]:
# YOUR CODE HERE
third = df_species.iloc[2]
print(third)

species             mole
weight              0.09
legs                 4.0
weight_in_lb    0.198416
Name: 4, dtype: object

In [81]:
assert 'third' in locals()
assert type(third) == pd.Series

## Access the row with INDEX `3` of `df_species`
And store it in `third_index`.

In [23]:
# YOUR CODE HERE
third_index = df_species.loc[3]
print(third_index)

species     dog
weight     20.0
legs        4.0
Name: 3, dtype: object

In [24]:
assert 'third_index' in locals()
assert type(third_index) == pd.Series

## Access the column `weight`
And store it in `weight`.

In [25]:
# YOUR CODE HERE
weight = df_species['weight']
print(weight)

6         0.0001
2         0.0200
4         0.0900
1         4.0000
3        20.0000
0        62.0000
7      3000.0000
5    200000.0000
Name: weight, dtype: float64

In [26]:
assert 'weight' in locals()
assert type(weight) == pd.Series

## Access the index and column labels
And store them as `index` and `columns`.

In [27]:
# YOUR CODE HERE
index = df_species.index
columns = df_species.columns
print(index)
print(columns)

Index([6, 2, 4, 1, 3, 0, 7, 5], dtype='int64')
Index(['species', 'weight', 'legs'], dtype='str')

In [28]:
assert 'index' in locals()
assert type(index) == pd.Index

In [29]:
assert 'columns' in locals()
assert type(columns) == pd.Index

## Extract the third row up until the fifth row into `df_slice`

In [30]:
# YOUR CODE HERE
df_slice = df_species.iloc[2:4]
print(df_slice)

  species  weight  legs
4    mole    0.09   4.0
1     cat    4.00   4.0

In [31]:
assert 'df_slice' in locals()
assert type(df_slice) == pd.DataFrame

## Extract rows without missing values into a new DataFrame into `df_non_empty`

In [32]:
# YOUR CODE HERE
df_non_empty = df_species.dropna()
df_non_empty

    species     weight  legs
6       bee     0.0001   6.0
2     mouse     0.0200   4.0
4      mole     0.0900   4.0
1       cat     4.0000   4.0
3       dog    20.0000   4.0
0     human    62.0000   2.0
7  elephant  3000.0000   4.0

In [33]:
assert 'df_non_empty' in locals()

## Obtain a summary table of the DataFrame with the means, standard deviations, min/max/percentiles of the numerical columns
Store it in `df_summary`

<div class="alert alert-block alert-info"><b>Hint: pandas has a nice convencience function for this.</</a></div>

In [34]:
# YOUR CODE HERE
df_summary = df_species.describe()
df_summary

              weight      legs
count       8.000000  7.000000
mean    25385.763762  4.000000
std     70562.543935  1.154701
min         0.000100  2.000000
25%         0.072500  4.000000
50%        12.000000  4.000000
75%       796.500000  4.000000
max    200000.000000  6.000000

In [35]:
assert 'df_summary' in locals()

## Add a new column `weight_in_lb` to the DataFrame containing the weights in pounds instead of kilograms
**For the sake of simplicity limit yourself to the first decimal of pounds when converting the weight.**

In [36]:
# YOUR CODE HERE
df_species['weight_in_lb'] = df_species['weight'] * 2.20462
df_species

    species       weight  legs   weight_in_lb
6       bee       0.0001   6.0       0.000220
2     mouse       0.0200   4.0       0.044092
4      mole       0.0900   4.0       0.198416
1       cat       4.0000   4.0       8.818480
3       dog      20.0000   4.0      44.092400
0     human      62.0000   2.0     136.686440
7  elephant    3000.0000   4.0    6613.860000
5     train  200000.0000   NaN  440924.000000

In [37]:
assert 'weight_in_lb' in df_species.columns

# Data Import

## Import the `df_characters.csv` file into a DataFrame `df_characters`, and display it.
Use the url from GitHub directly: `https://raw.githubusercontent.com/Practical-Integrative-Bioinformatics/Introduction/refs/heads/main/example_data/df_characters.csv`.

In [38]:
# YOUR CODE HERE
url = 'https://raw.githubusercontent.com/Practical-Integrative-Bioinformatics/Introduction/refs/heads/main/example_data/df_characters.csv'
df_characters = pd.read_csv(url)
df_characters

                   name country   species       weight  birthyear
0               Pumuckl     GER    kobold       2.0000       1982
1                   Tom     USA       cat       3.0000       1940
2                 Jerry     USA     mouse       0.3000       1940
3          Mickey Mouse     USA     mouse      10.0000       1928
4               Asterix     FRA     human      58.0000       1959
5                Obelix     FRA     human     180.0000       1959
6           Hello Kitty     JPN       cat       0.7000       1974
7               Songoku     JPN     human      62.0000       1984
8        Maulwurf Krtek     CZE      mole       0.1000       1956
9                Tintin     BEL     human      54.0000       1929
10               Thomas     GBR     train  115000.0000       1984
11           Biene Maja     GER       bee       0.0001       1975
12                 Gary     USA     snail       0.0500       1999
13                Babar     CAN  elephant    2000.0000       1989
14    Benjamin Blümchen     GER  elephant     800.0000       1988
15  Prinzessin Lillifee     GER     human      30.0000       2004

In [39]:
assert 'df_characters' in locals()

## Now import the `df_countries.tsv` into a pandas DataFrame as `df_countries`. Do you need to change any parameters of the importing function?

Use the url from GitHub directly: `https://raw.githubusercontent.com/Practical-Integrative-Bioinformatics/Introduction/refs/heads/main/example_data/df_countries.tsv`.

In [40]:
# YOUR CODE HERE
url = 'https://raw.githubusercontent.com/Practical-Integrative-Bioinformatics/Introduction/refs/heads/main/example_data/df_countries.tsv'
df_countries = pd.read_csv(url, sep='\t')
df_countries

  code                   country continent  population
0  GER                   Germany    Europe        83.0
1  USA  United States of America   America       327.0
2  FRA                    France    Europe        67.0
3  JPN                     Japan      Asia       127.0
4  CZE            Czech Republic    Europe        10.5
5  BEL                   Belgium    Europe        11.3
6  GBR            United Kingdom    Europe        66.0
7  CHN                     China      Asia      1386.0
8  CAN                    Canada   America        37.0
9  BRA                    Brazil   America       210.0

In [41]:
assert 'df_countries' in locals()

# DataFrame filtering
## Using `df_characters` apply the following filters (separately) and display the results:

### All German characters
Store the result in `Germans`.

In [42]:
# YOUR CODE HERE
germans = df_characters[df_characters['country'] == 'GER']
print(germans)

                   name country   species    weight  birthyear
0               Pumuckl     GER    kobold    2.0000       1982
11           Biene Maja     GER       bee    0.0001       1975
14    Benjamin Blümchen     GER  elephant  800.0000       1988
15  Prinzessin Lillifee     GER     human   30.0000       2004

In [43]:
assert 'germans' in locals()

### Characters born after 1970
Store the result in `seventies`.

In [44]:
# YOUR CODE HERE
seventies = df_characters[df_characters['birthyear'] >= 1970]
print(seventies)

                   name country   species       weight  birthyear
0               Pumuckl     GER    kobold       2.0000       1982
6           Hello Kitty     JPN       cat       0.7000       1974
7               Songoku     JPN     human      62.0000       1984
10               Thomas     GBR     train  115000.0000       1984
11           Biene Maja     GER       bee       0.0001       1975
12                 Gary     USA     snail       0.0500       1999
13                Babar     CAN  elephant    2000.0000       1989
14    Benjamin Blümchen     GER  elephant     800.0000       1988
15  Prinzessin Lillifee     GER     human      30.0000       2004

In [45]:
assert 'seventies' in locals()

### Human characters weighing <60 kg
Store the result in `less_than_sixty`.

In [46]:
# YOUR CODE HERE
less_than_sixty = df_characters[df_characters['weight'] < 60]
print(less_than_sixty)

                   name country species   weight  birthyear
0               Pumuckl     GER  kobold   2.0000       1982
1                   Tom     USA     cat   3.0000       1940
2                 Jerry     USA   mouse   0.3000       1940
3          Mickey Mouse     USA   mouse  10.0000       1928
4               Asterix     FRA   human  58.0000       1959
6           Hello Kitty     JPN     cat   0.7000       1974
8        Maulwurf Krtek     CZE    mole   0.1000       1956
9                Tintin     BEL   human  54.0000       1929
11           Biene Maja     GER     bee   0.0001       1975
12                 Gary     USA   snail   0.0500       1999
15  Prinzessin Lillifee     GER   human  30.0000       2004

In [47]:
assert 'less_than_sixty' in locals()

## Introduce a column named `age` based on the characters' birthdates.

In [48]:
# YOUR CODE HERE
df_characters['age'] = 2026 - df_characters['birthyear']

In [49]:
assert 'age' in df_characters.columns

## What is the average age of the characters?
Store it in `avg_age`.

In [50]:
# YOUR CODE HERE
avg_age = df_characters['age'].mean()
print(avg_age)

57.875

In [51]:
assert 'avg_age' in locals()

## Who is the youngest German character?
Store the corresponding row in `youngest_german`.

In [52]:
# YOUR CODE HERE
germans = df_characters[df_characters['country'] == 'GER']
youngest_german = germans.loc[germans['age'].idxmin()]
print(youngest_german)

name         Prinzessin Lillifee
country                      GER
species                    human
weight                      30.0
birthyear                   2004
age                           22
Name: 15, dtype: object

In [53]:
assert 'youngest_german' in locals()

# DataFrame aggregation

Using `df_characters`

## Count the number of characters from each country
And store it as series `chars_per_country`

In [54]:
# YOUR CODE HERE
chars_per_country = df_characters['country'].value_counts()
print(chars_per_country)

country
GER    4
USA    4
FRA    2
JPN    2
CZE    1
BEL    1
GBR    1
CAN    1
Name: count, dtype: int64

In [55]:
assert 'chars_per_country' in locals()

## Calculate the average weight and age of characters by species
Store the result in `df_characters_avg`. The new dataframe should only contain the columns `species`, `avg_weight` and `avg_age`.

In [56]:
# YOUR CODE HERE
df_characters_avg = df_characters.groupby('species', as_index=False).agg(
    avg_weight=('weight', 'mean'),
    avg_age=('age', 'mean'))
df_characters_avg

    species   avg_weight  avg_age
0       bee       0.0001     51.0
1       cat       1.8500     69.0
2  elephant    1400.0000     37.5
3     human      76.8000     59.0
4    kobold       2.0000     44.0
5      mole       0.1000     70.0
6     mouse       5.1500     92.0
7     snail       0.0500     27.0
8     train  115000.0000     42.0

In [57]:
assert 'df_characters_avg' in locals()
assert 'avg_weight' in df_characters_avg.columns
assert 'avg_age' in df_characters_avg.columns

## List the heaviest characters per country
Store the result in `df_chars_heaviest`. The new dataframe should only contain the columns `country`, `name`, `weight`.

In [58]:
# YOUR CODE HERE
heaviest_indices = df_characters.groupby('country')['weight'].idxmax()
df_chars_heaviest = df_characters.loc[heaviest_indices, ['country', 'name', 'weight']]
df_chars_heaviest

   country               name    weight
9      BEL             Tintin      54.0
13     CAN              Babar    2000.0
8      CZE     Maulwurf Krtek       0.1
5      FRA             Obelix     180.0
10     GBR             Thomas  115000.0
14     GER  Benjamin Blümchen     800.0
7      JPN            Songoku      62.0
3      USA       Mickey Mouse      10.0

In [59]:
assert 'df_chars_heaviest' in locals()
assert 'name' in df_chars_heaviest.columns
assert 'weight' in df_chars_heaviest.columns

# Joining (or merging) DataFrames
We now have three dataframes: `df_species`, `df_characters` and `df_countries`. Take another look at all of them and try to come up with a way to combine their information.
Create another dataframe called `df_merge` including all three dataframes. There are some things you should consider, when you create your new dataframe:
1. We are going to use our characters from `df_characters` as main target, so leave out all countries or species without one.
2. Character and species each have weights, use `weight_indiv` for a characters weight and `weight_species` for the species weight.
3. Countries have a column `country` and `code`, think about which you should use as a key to join your dataframes.
4. Try to solve this task using (mostly) the `merge` function in pandas.

<div class="alert alert-block alert-info"><b>Hint: Should you struggle or just want to compare your result, you can take a look at the merged dataframe <a href=https://github.com/Practical-Integrative-Bioinformatics/Introduction/blob/main/example_data/day1.tsv>here</a>.</</a></div> Watch out, as this is not going to look exactly like your dataframe, as this contains additional columns and different ages.

In [60]:
# YOUR CODE HERE
#inner merge, since only countries and species that are in df_characters are kept
df_merge = pd.merge(df_characters, df_countries, left_on='country', right_on='code', how = 'left')
df_merge
df_merge = pd.merge(df_merge, df_species, left_on='species', right_on='species', how = 'left')
df_merge

,name,country_x,species,weight_x,birthyear,age,code,country_y,continent,population,weight_y,legs,weight_in_lb
0,Pumuckl,GER,kobold,2.0000,1982,44,GER,Germany,Europe,83.0,NaN,NaN,NaN
1,Tom,USA,cat,3.0000,1940,86,USA,United States of America,America,327.0,4.0000,4.0,8.818480
2,Jerry,USA,mouse,0.3000,1940,86,USA,United States of America,America,327.0,0.0200,4.0,0.044092
3,Mickey Mouse,USA,mouse,10.0000,1928,98,USA,United States of America,America,327.0,0.0200,4.0,0.044092
4,Asterix,FRA,human,58.0000,1959,67,FRA,France,Europe,67.0,62.0000,2.0,136.686440
5,Obelix,FRA,human,180.0000,1959,67,FRA,France,Europe,67.0,62.0000,2.0,136.686440
6,Hello Kitty,JPN,cat,0.7000,1974,52,JPN,Japan,Asia,127.0,4.0000,4.0,8.818480
7,Songoku,JPN,human,62.0000,1984,42,JPN,Japan,Asia,127.0,62.0000,2.0,136.686440
8,Maulwurf Krtek,CZE,mole,0.1000,1956,70,CZE,Czech Republic,Europe,10.5,0.0900,4.0,0.198416
9,Tintin,BEL,human,54.0000,1929,97,BEL,Belgium,Europe,11.3,62.0000,2.0,136.686440
10,Thomas,GBR,train,115000.0000,1984,42,GBR,United Kingdom,Europe,66.0,200000.0000,NaN,440924.000000
11,Biene Maja,GER,bee,0.0001,1975,51,GER,Germany,Europe,83.0,0.0001,6.0,0.000220
12,Gary,USA,snail,0.0500,1999,27,USA,United States of America,America,327.0,NaN,NaN,NaN
13,Babar,CAN,elephant,2000.0000,1989,37,CAN,Canada,America,37.0,3000.0000,4.0,6613.860000
14,Benjamin Blümchen,GER,elephant,800.0000,1988,38,GER,Germany,Europe,83.0,3000.0000,4.0,6613.860000
15,Prinzessin Lillifee,GER,human,30.0000,2004,22,GER,Germany,Europe,83.0,62.0000,2.0,136.686440

In [61]:
assert 'df_merge' in locals()

## Using our new `df_merge` try to answer: what is the average age of four-legged characters?
Store the result in `avg_age_four_legs`.

In [62]:
# YOUR CODE HERE
avg_age_four_legs = df_merge[df_merge['legs'] == 4]['age'].mean()
avg_age_four_legs

np.float64(66.71428571428571)

In [63]:
assert 'avg_age_four_legs' in locals()

## What is the average weight of four-legged characters?
Store the result in `avg_weight_four_legs`.

In [64]:
# YOUR CODE HERE
avg_weight_four_legs = df_merge[df_merge['legs'] == 4]['weight_x'].mean()
avg_weight_four_legs

np.float64(402.0142857142857)

In [65]:
assert 'avg_weight_four_legs' in locals()

## Compute the characters' relative weight as a percentage of the typical weight of their species and add it as a new column `rel_weight`. Are there any characters you couldn't compute this for?

In [66]:
# YOUR CODE HERE
df_merge['rel_weight'] = df_merge['weight_x'] / df_merge['weight_y']
df_merge

,name,country_x,species,weight_x,birthyear,age,code,country_y,continent,population,weight_y,legs,weight_in_lb,rel_weight
0,Pumuckl,GER,kobold,2.0000,1982,44,GER,Germany,Europe,83.0,NaN,NaN,NaN,NaN
1,Tom,USA,cat,3.0000,1940,86,USA,United States of America,America,327.0,4.0000,4.0,8.818480,0.750000
2,Jerry,USA,mouse,0.3000,1940,86,USA,United States of America,America,327.0,0.0200,4.0,0.044092,15.000000
3,Mickey Mouse,USA,mouse,10.0000,1928,98,USA,United States of America,America,327.0,0.0200,4.0,0.044092,500.000000
4,Asterix,FRA,human,58.0000,1959,67,FRA,France,Europe,67.0,62.0000,2.0,136.686440,0.935484
5,Obelix,FRA,human,180.0000,1959,67,FRA,France,Europe,67.0,62.0000,2.0,136.686440,2.903226
6,Hello Kitty,JPN,cat,0.7000,1974,52,JPN,Japan,Asia,127.0,4.0000,4.0,8.818480,0.175000
7,Songoku,JPN,human,62.0000,1984,42,JPN,Japan,Asia,127.0,62.0000,2.0,136.686440,1.000000
8,Maulwurf Krtek,CZE,mole,0.1000,1956,70,CZE,Czech Republic,Europe,10.5,0.0900,4.0,0.198416,1.111111
9,Tintin,BEL,human,54.0000,1929,97,BEL,Belgium,Europe,11.3,62.0000,2.0,136.686440,0.870968
10,Thomas,GBR,train,115000.0000,1984,42,GBR,United Kingdom,Europe,66.0,200000.0000,NaN,440924.000000,0.575000
11,Biene Maja,GER,bee,0.0001,1975,51,GER,Germany,Europe,83.0,0.0001,6.0,0.000220,1.000000
12,Gary,USA,snail,0.0500,1999,27,USA,United States of America,America,327.0,NaN,NaN,NaN,NaN
13,Babar,CAN,elephant,2000.0000,1989,37,CAN,Canada,America,37.0,3000.0000,4.0,6613.860000,0.666667
14,Benjamin Blümchen,GER,elephant,800.0000,1988,38,GER,Germany,Europe,83.0,3000.0000,4.0,6613.860000,0.266667
15,Prinzessin Lillifee,GER,human,30.0000,2004,22,GER,Germany,Europe,83.0,62.0000,2.0,136.686440,0.483871

In [67]:
assert 'rel_weight' in df_merge.columns

## How many characters are there from each continent?
Store the result in `chars_per_continent`.

In [68]:
# YOUR CODE HERE
chars_per_continent = df_merge['continent'].value_counts()
chars_per_continent

continent
Europe     9
America    5
Asia       2
Name: count, dtype: int64

In [69]:
assert 'chars_per_continent' in locals()

## Which character comes from the smallest country (by population)?
Store the row in `smallest_country`.

In [70]:
# character from the smallest country
#dfm.sort_values('population').iloc[0]
#dfm.loc[dfm['population'] == dfm['population'].min()]
smallest_country = df_merge.loc[df_merge['population'].idxmin()]
smallest_country

name            Maulwurf Krtek
country_x                  CZE
species                   mole
weight_x                   0.1
birthyear                 1956
age                         70
code                       CZE
country_y       Czech Republic
continent               Europe
population                10.5
weight_y                  0.09
legs                       4.0
weight_in_lb          0.198416
rel_weight            1.111111
Name: 8, dtype: object

In [71]:
assert 'smallest_country' in locals()

## Who is the most overweight European character?
Store the row in `overweight_european`.

In [72]:
# YOUR CODE HERE
overweight_european = df_merge.loc[df_merge.loc[df_merge['continent'] == 'Europe', 'rel_weight'
].idxmax()]
overweight_european

name               Obelix
country_x             FRA
species             human
weight_x            180.0
birthyear            1959
age                    67
code                  FRA
country_y          France
continent          Europe
population           67.0
weight_y             62.0
legs                  2.0
weight_in_lb    136.68644
rel_weight       2.903226
Name: 5, dtype: object

In [73]:
assert 'overweight_european' in locals()

# Data export

## Create a full outer merge of the three DataFrames with question marks in place of N/A values
Store it as `df_export`.

In [74]:
# YOUR CODE HERE
df_export = pd.merge(df_characters, df_countries, left_on='country', right_on='code', how = 'outer')
df_export = pd.merge(df_export, df_species, left_on='species', right_on='species', how = 'outer')
df_export = df_export.fillna('?')
df_export

,name,country_x,species,weight_x,birthyear,age,code,country_y,continent,population,weight_y,legs,weight_in_lb
0,Biene Maja,GER,bee,0.0001,1975.0,51.0,GER,Germany,Europe,83.0,0.0001,6.0,0.00022
1,Hello Kitty,JPN,cat,0.7,1974.0,52.0,JPN,Japan,Asia,127.0,4.0,4.0,8.81848
2,Tom,USA,cat,3.0,1940.0,86.0,USA,United States of America,America,327.0,4.0,4.0,8.81848
3,?,?,dog,?,?,?,?,?,?,?,20.0,4.0,44.0924
4,Babar,CAN,elephant,2000.0,1989.0,37.0,CAN,Canada,America,37.0,3000.0,4.0,6613.86
5,Benjamin Blümchen,GER,elephant,800.0,1988.0,38.0,GER,Germany,Europe,83.0,3000.0,4.0,6613.86
6,Tintin,BEL,human,54.0,1929.0,97.0,BEL,Belgium,Europe,11.3,62.0,2.0,136.68644
7,Asterix,FRA,human,58.0,1959.0,67.0,FRA,France,Europe,67.0,62.0,2.0,136.68644
8,Obelix,FRA,human,180.0,1959.0,67.0,FRA,France,Europe,67.0,62.0,2.0,136.68644
9,Prinzessin Lillifee,GER,human,30.0,2004.0,22.0,GER,Germany,Europe,83.0,62.0,2.0,136.68644
10,Songoku,JPN,human,62.0,1984.0,42.0,JPN,Japan,Asia,127.0,62.0,2.0,136.68644
11,Pumuckl,GER,kobold,2.0,1982.0,44.0,GER,Germany,Europe,83.0,?,?,?
12,Maulwurf Krtek,CZE,mole,0.1,1956.0,70.0,CZE,Czech Republic,Europe,10.5,0.09,4.0,0.198416
13,Jerry,USA,mouse,0.3,1940.0,86.0,USA,United States of America,America,327.0,0.02,4.0,0.044092
14,Mickey Mouse,USA,mouse,10.0,1928.0,98.0,USA,United States of America,America,327.0,0.02,4.0,0.044092
15,Gary,USA,snail,0.05,1999.0,27.0,USA,United States of America,America,327.0,?,?,?
16,Thomas,GBR,train,115000.0,1984.0,42.0,GBR,United Kingdom,Europe,66.0,200000.0,?,440924.0
17,?,?,?,?,?,?,BRA,Brazil,America,210.0,?,?,?
18,?,?,?,?,?,?,CHN,China,Asia,1386.0,?,?,?

In [75]:
assert 'df_export' in locals()

# Optional extra tasks:

## List characters that are the sole entries of their country
Store the result in `sole_chars`.

In [76]:
# YOUR CODE HERE
country_counts = df_merge['country_x'].value_counts()
sole_countries = country_counts[country_counts == 1].index
sole_chars = df_merge[df_merge['country_x'].isin(sole_countries)]
sole_chars

,name,country_x,species,weight_x,birthyear,age,code,country_y,continent,population,weight_y,legs,weight_in_lb,rel_weight
8,Maulwurf Krtek,CZE,mole,0.1,1956,70,CZE,Czech Republic,Europe,10.5,0.09,4.0,0.198416,1.111111
9,Tintin,BEL,human,54.0,1929,97,BEL,Belgium,Europe,11.3,62.00,2.0,136.686440,0.870968
10,Thomas,GBR,train,115000.0,1984,42,GBR,United Kingdom,Europe,66.0,200000.00,NaN,440924.000000,0.575000
13,Babar,CAN,elephant,2000.0,1989,37,CAN,Canada,America,37.0,3000.00,4.0,6613.860000,0.666667

In [77]:
assert 'sole_chars' in locals()

## Count characters by decade of birth -- without explicitly inserting a new column
Store the resulting series in `decades`.

In [78]:
# YOUR CODE HERE
decades = (df_characters['birthyear'] // 10 * 10).value_counts().sort_index()
decades

birthyear
1920    2
1940    2
1950    3
1970    2
1980    5
1990    1
2000    1
Name: count, dtype: int64

In [79]:
assert 'decades' in locals()